### ISSUE TITLE
When I ran the k-pbc code, I didn't quite understand how to create the demo.txt file. I hope the professor can help me solve my doubts

### ISSUE THREAD

**Issue by EvenZ2001** [ClarkDinh/k-PbC#1]
When I ran the k-pbc code, I didn't quite understand how to create the demo.txt file. I hope the professor can help me solve my doubts

**Comment by taiduydinh** [comment]
Hi EvenZ2001, I am sorry I missed your message.

I just optimized the code of k-PbC to prepare for a new project.
What problems do you have?
If you want to run k-PbC, you can use the code I uploaded to the respository yesterday.
If you have any questions, please send it to my email: it08duytai@gmail.com
